spring:
  h2:
    console:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:themoviedbclone
    username: h2
    password:
#    url: jdbc:mysql://localhost/themoviedb_clone_teste?createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: root
#    password: docker 
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  
  